### ISSUE TITLE
TestDll fails to build when project path has spaces (error MSB3073)

### ISSUE THREAD

**Issue by tfburns** [AI-TOOLKIT/VoiceBridge#1]
### Description

Following the installation instructions I am unable to build the release or debug x64 builds of the TestDll if the project path contains spaces.

### Version & Hardware

**Operating System version:** Windows 10 Home 64-bit

**Computer:** i7 CPU, 16GB RAM

**Computer Processors/Cores:** 4 cores

**Visual Studio Version:** Visual Studio Community 2017 (version 15.9.28)

**Visual Studio Coniguration:** [Enter here the VS configuration you use e.g. Release 64-bit.]

### Steps to Reproduce In Case Of An Error

1. Follow installation instructions as described.
2. Attempt to build TestDll

**Expected behavior:** Expect no errors

**Actual behavior:** Get error

**Reproduces how often:** 100%

### Which Steps Have You Tried To Debug The Problem In Case Of An Error

The error message led me to this StackOverflow question/answer (https://stackoverflow.com/questions/39287170/visual-studio-post-build-xcopy-dont-work-error-msb3073-vcend-exited-with-co), which suggested that spaces in the file path may be the problem. I fixed the issue by just putting the files in a directory without spaces in the folder names. I suggest a note be added to the readme.

### Logs

Build output if the :

```
1>------ Build started: Project: TestDll, Configuration: Debug x64 ------
1>Invalid number of parameters
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: The command "xcopy /Y "E:\[long path with some spaces]\VoiceBridge\VoiceBridge\TestDll\TestDll\..\..\VoiceBridge\x64\Debug\VoiceBridge.dll" E:\[long path with some spaces]\VoiceBridge\VoiceBridge\TestDll\x64\Debug\
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(128,5): error MSB3073: :VCEnd" exited with code 4.
1>Done building project "TestDll.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
N.B. I edited the file paths in the message above for privacy and because they were long.

**Comment by tfburns** [comment]
I opened a pull request #2 to add a note in the installation instructions to address this issue.

**Comment by AI-TOOLKIT** [comment]
Hello Tom,
The xcopy commands in the VoiceBridge project file contain apostrophes which prevent this problem. Is it possible that you have removed these apostrophes? Also the link you have posted does not contain any mention of spaces in the path.
Br,
Zoltan

**Comment by tfburns** [comment]
Hi Zoltan,
I didn't remove anything so am not sure why this error occurred in that case. Perhaps a system version issue or similar?
Apologies, that link doesn't mention spaces. Perhaps it was another question/answer which mentioned them. In any case, my solution of moving it to another path without spaces worked for me.
Best,
Tom

**Comment by AI-TOOLKIT** [comment]
Thank you Tom! I have found the problem. The second variable in the xcopy function does not have the apostrophe. 
The project file contains:
  xcopy /Y "$(ProjectDir)..\..\VoiceBridge\x64\Debug\VoiceBridge.dll" $(TargetDir)
but it should be
  xcopy /Y "$(ProjectDir)..\..\VoiceBridge\x64\Debug\VoiceBridge.dll" "$(TargetDir)"

Your target directory must be between apostrophes! I will correct the code and post the new version.

**Comment by tfburns** [comment]
Great, thanks! I guess the PR #2 I made is redundant if that fix is deployed :)
